In [1]:
import opencv as cv

ModuleNotFoundError: No module named 'opencv'

In [3]:
!pip install opencv-python

    100% |████████████████████████████████| 25.0MB 32kB/s eta 0:00:01015% |█▊                              | 1.4MB 2.2MB/s eta 0:00:11    9% |███▏                            | 2.5MB 2.4MB/s eta 0:00:10    12% |████                            | 3.1MB 2.1MB/s eta 0:00:11    25% |████████                        | 6.3MB 1.8MB/s eta 0:00:11    32% |██████████▍                     | 8.1MB 2.5MB/s eta 0:00:07    36% |███████████▋                    | 9.1MB 2.3MB/s eta 0:00:07    38% |████████████▍                   | 9.7MB 2.9MB/s eta 0:00:06    39% |████████████▊                   | 10.0MB 3.2MB/s eta 0:00:05    42% |█████████████▌                  | 10.5MB 2.9MB/s eta 0:00:05    44% |██████████████▍                 | 11.2MB 3.1MB/s eta 0:00:05    48% |███████████████▍                | 12.0MB 2.5MB/s eta 0:00:06    51% |████████████████▋               | 12.9MB 2.2MB/s eta 0:00:06    56% |██████████████████▏             | 14.2MB 2.6MB/s eta 0:00:05    57% |██████████████████▌             | 14

In [2]:
import cv2
import numpy as np

In [5]:
arr = np.ones((3,2,4))

In [9]:
arr[0:2,0:1,:]

array([[[ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.]]])

In [14]:
image = np.ones((3,1,7), dtype=np.uint8) * 255

In [15]:
image

array([[[255, 255, 255, 255, 255, 255, 255]],

       [[255, 255, 255, 255, 255, 255, 255]],

       [[255, 255, 255, 255, 255, 255, 255]]], dtype=uint8)

In [16]:
y_true = np.array([0,1,0,0,0])
y_pred = np.ones(5, dtype=np.int32)

In [18]:
y_true == y_pred

array([False,  True, False, False, False], dtype=bool)

In [19]:
l = [1,2,3]
s = [1,4,5]
l == s

False

In [20]:
t_positive = (y_true == 1)

In [21]:
t_positive

array([False,  True, False, False, False], dtype=bool)

In [22]:
np.random.rand(10)

array([ 0.47696747,  0.67875514,  0.63202218,  0.80192011,  0.69721946,
        0.91758322,  0.24361417,  0.50996892,  0.94112351,  0.64967114])